# data-flow package
from .boolean_obfuscator import split_booleans_from_source
from .interger_obfuscator import obfuscate_integers_preserve_pragma
from .local_state_obfuscator import convert_locals_to_state
from .scalar_splitter import split_scalar_variables
from .static_data_obfuscator import transform_static_to_dynamic